services:
  jellyfin:
    container_name: ctr-jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    env_file: .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #ports:
    #  - "8096:8096" # HTTP
    #  - "8920:8920" # HTTPs
    #  - "7359:7359/udp" # Client Discovery
    volumes:
      - ./config:/config
      - ./cache:/cache
      #- str:/media # If you want to use external storage
      - ./media:/media # Remove if you want to use external storage
    networks:
      jellyfin:
        ipv4_address: 10.1.23.2

networks:
  jellyfin:
    name: net-jellyfin
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.23.0/24
         gateway: 10.1.23.1

#volumes:
#  str:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//host/share"
#      o: "username=username,password=password,uid=1000,gid=1000"