services:
  <SERVICE_NAME>:
    container_name: ctr-<SERVICE_NAME>
    image: <IMAGE_NAME>
    restart: unless-stopped
    #env_file: .env
    #ports:
    #  - "<HOST_PORT>:<CONTAINER_PORT>"
    #volumes:
    #  - ./data:/data
    networks:
      #net-databases:
      <SERVCIE_NAME>:
        ipv4_address: 10.0.0.2

networks:
  <SERVCIE_NAME>:
    name: <NETWORK_NAME>
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24
         gateway: 10.0.0.1
  #net-databases:
  #  external: true
  