services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    env_file: .env
    ports:
      - target: 22
        published: 222
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - forgejo
      - caddy
      - databases
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  forgejo:
    name: net-forgejo
    driver: overlay
    attachable: true
  caddy:
    external: true
    name: net-caddy
  databases:
    external: true
    name: net-databases
