services:
  server:
    image: codeberg.org/forgejo/forgejo:10
    env_file: .env
    ports:
      - target: 22
        published: 222
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - forgejo
      - caddy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  forgejo:
    name: net-forgejo
    driver: overlay
  caddy:
    external: true
    name: net-caddy
