services:
  server:
    image: data.forgejo.org/forgejo/runner:4.0.0
    user: root
    env_file: .env
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'
    #command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  forgejo:
    name: net-forgejo
    external: true
