services:
  api:
    container_name: ctr-velld-api
    image: ghcr.io/dendianugerah/velld/api:latest
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - "8080:8080"
    volumes:
      #- str:/app/backups # If you want to use external storage.
      - ./backups:/app/backups # Remove if you use external storage
      - ./data:/app/data
    networks:
      velld:
        ipv4_address: 10.1.40.2

  web:
    container_name: ctr-velld-web
    image: ghcr.io/dendianugerah/velld/web:latest
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - "3000:3000"
    networks:
      velld:
        ipv4_address: 10.1.40.3

#volumes:
#  str:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//host/share"
#      o: "username=username,password=password,uid=1000,gid=1000"

networks:
  velld:
    name: net-velld
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.40.0/24
         gateway: 10.1.40.1