services:
  vaultwarden:
    image: vaultwarden/server # For OAuth (11.10.2024): timshel/vaultwarden:latest-alpine
    volumes:
       - ./data:/data
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
    env_file: .env
    networks:
      vaultwarden:
        ipv4_address: 10.5.0.2
    restart: unless-stopped
    container_name: VaultWarden

networks:
  vaultwarden:
    name: VaultWarden
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1