services:
  syncthing:
    container_name: ctr-syncthing
    image: lscr.io/linuxserver/syncthing
    restart: unless-stopped
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./config:/config
      - ./data:/data
      #- str:/data # If you want to use external storage
    networks:
      syncthing:
        ipv4_address: 10.1.16.2

networks:
  syncthing:
    name: net-syncthing
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.16.0/24
         gateway: 10.1.16.1

#volumes:
#  str:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//host/share"
#      o: "username=,password=,uid=1000,gid=1000,file_mode=0777,dir_mode=0777"
