services:
  server:
    image: registry:2
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    command: registry serve /root/config.yml
    volumes:
      #- str:/var/lib/registry If you want to use external storage
      - ./data:/var/lib/registry
      - ./config.yml:/root/config.yml
    networks:
      - registry
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  registry:
    name: net-registry
    driver: overlay

#volumes:
#  str:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//host/share"
#      o: "username=username,password=password,uid=1000,gid=1000"