services:
  agent:
    image: portainer/agent
    networks:
      - portainer
    ports:
      - "9001:9001"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

networks:
  portainer:
    driver: overlay