services:
  server:
    image: mariadb
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - databases
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  databases:
    name: net-databases
    driver: overlay
    attachable: true
