services:
  agent:
    image: henrygd/beszel-agent
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure