services:
  server:
    image: lscr.io/linuxserver/phpmyadmin
    env_file: .env
    volumes:
      - ./config:/config
    networks:
      - databases
      - caddy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  databases:
    name: net-databases
    driver: overlay
    external: true
  caddy:
    name: net-caddy
    external: true