services:
  caddy:
    container_name: ctr-caddy
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./sites:/etc/caddy/
    networks:
      caddy:
        ipv4_address: 10.1.1.2

networks:
  caddy:
    name: net-caddy
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.1.0/24
         gateway: 10.1.1.1