services:
  adguard:
    container_name: ctr-adguard
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      #- "5443:5443/udp" # DNSCrypt
      #- "5443:5443/tcp" # DNSCrypt
      #- "8853:8853/udp" # DNS over QUIC
      #- "853:853/udp" # DNS over QUIC
      #- "784:784/udp" # DNS over QUIC
      #- "853:853/tcp" # DNS over QUIC
      #- "3000:3000/tcp" # Web interface
      #- "443:443/udp" # DNS over HTTPS
      #- "443:443/tcp" # DNS over HTTPS
      #- "80:80/tcp" # DNS over HTTPS
      #- "68:68/udp" # DHCP
      #- "67:67/udp" # DHCP
      - "53:53/udp" # Plain DNS
      - "53:53/tcp" # Plain DNS
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    networks:
      adguard:
        ipv4_address: 10.1.14.2

networks:
  adguard:
    name: net-adguard
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.14.0/24
         gateway: 10.1.14.1
  