services:
  beszel-agent:
    container_name: ctr-beszel-agent
    image: henrygd/beszel-agent
    restart: unless-stopped
    network_mode: host
    env_file: .env
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro