services:
  portainer:
    container_name: ctr-portainer
    image: ngxson/portainer-ce-without-annoying:latest
    restart: unless-stopped
    #ports:
    #  - "9000:9000"
    volumes:
       - ./data:/data
       - /var/run/docker.sock:/var/run/docker.sock
    networks:
      portainer:
        ipv4_address: 10.1.2.2

networks:
  portainer:
    name: net-portainer
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.2.0/24
         gateway: 10.1.2.1