services:
  portainer:
    image: ngxson/portainer-ce-without-annoying:latest
    volumes:
       - ./data:/data
       - /var/run/docker.sock:/var/run/docker.sock
    networks:
      portainer:
        ipv4_address: 10.1.0.2
    restart: unless-stopped
    container_name: Portainer

networks:
  portainer:
    name: Portainer
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/16
         gateway: 10.1.0.1