services:
  beszel_hub:
    image: henrygd/beszel
    volumes:
       - ./data:/beszel_data
    networks:
      beszel:
        ipv4_address: 10.6.0.2
    restart: unless-stopped
    container_name: Beszel-Hub
    extra_hosts:
      - 'host.docker.internal:host-gateway' # For same host (see https://github.com/henrygd/beszel/blob/main/supplemental/docker/same-system/docker-compose.yml)

  beszel_agent:
    image: henrygd/beszel-agent
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    restart: unless-stopped
    container_name: Beszel-Agent
    env_file: .env

networks:
  beszel:
    name: Beszel
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1