services:
  beszel-hub:
    container_name: ctr-beszel-hub
    image: henrygd/beszel
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway' # For same host (see https://github.com/henrygd/beszel/blob/main/supplemental/docker/same-system/docker-compose.yml)
    #ports:
    #  - "8090:8090"
    volumes:
      - ./data:/beszel_data
    networks:
      beszel:
        ipv4_address: 10.1.4.2

networks:
  beszel:
    name: net-beszel
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.4.0/24
         gateway: 10.1.4.1