services:
  mariadb:
    image: mariadb:11
    env_file: '.env'
    volumes:
      - './data:/var/lib/mysql'
    healthcheck:
        test:
            - CMD
            - healthcheck.sh
            - '--su-mysql'
            - '--connect'
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 5s
    networks:
      databases:
        ipv4_address: 10.2.0.254
    restart: unless-stopped
    container_name: MariaDB

networks:
  databases:
    name: databases
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16
         gateway: 10.2.0.1