services:
  server:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - uptime-kuma
      - caddy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  uptime-kuma:
    name: net-uptime-kuma
    driver: overlay
  caddy:
    name: net-caddy
    external: true