services:
  phpmyadmin:
    container_name: ctr-phpmyadmin
    image: lscr.io/linuxserver/phpmyadmin
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - "80:80"
    volumes:
      - ./config:/config
    networks:
      net-databases:

networks:
  net-databases:
    external: true
  