services:
  portainer-agent:
    container_name: ctr-portainer-agent
    image: portainer/agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
       - /var/lib/docker/volumes:/var/lib/docker/volumes
       - /var/run/docker.sock:/var/run/docker.sock
       - /:/host
    networks:
      portainer-agent:
        ipv4_address: 10.1.3.2

networks:
  portainer-agent:
    name: net-portainer-agent
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.3.0/24
         gateway: 10.1.3.1
  